org.cobolaci.hackaton.greenbrno:
  providers:
    arcgis:
      baseUrl: https://services6.arcgis.com/fUWVlHWZNxUvTUh8/arcgis/rest/services/
    stravaapi:
      baseUrl: https://www.strava.com/api/v3/
      authorization: ${STRAVA_OAUTH_TOKEN}
  data-sources:
    bike-to-work:
      path: dpnk_data/FeatureServer/0/query
      queryParams:
        outFields: data_2019,data_2020,data_2021,Shape__Length
        where: 1=1
        returnGeometry: false
        returnCountOnly: false
        outSR: 4326
        f: json
    cyclist-intensity:
      path: Cyklodetektory_h/FeatureServer/0/query
      queryParams:
        outFields: ID,UnitName,EndOfInterval,FirstDirection_Cyclists,FirstDirection_Pedestrians,FirstDirection_Total,SecondDirection_Cyclists,SecondDirection_Pedestrians,SecondDirection_Total,datum,LocationId
        where: 1=1
        returnGeometry: true
        returnCountOnly: false
        outSR: 4326
        f: json
    greenery:
      path: stromy_kere/FeatureServer/0/query
      queryParams:
        outFields: ogcfid,druh_bio_kod,nazev
        where: 1=1
        returnGeometry: true
        returnCountOnly: false
        outSR: 4326
        f: json
    strava-club-activities:
      path: /clubs/209965/activities

logging:
  level:
    org.springframework: DEBUG